In [2]:
import numpy as np 

In [7]:
%timeit a = 2

11 ns ± 0.612 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [12]:
arr2D = np.array([ [ 1 ,2 ,3 ] ,[1,2,3] ])
print (arr2D ) 
print ( arr2D.ndim) 


[[1 2 3]
 [1 2 3]]
2


In [13]:
arr3d = np.array([[[1,2,3] , [1,4,5] ] ,[ [1,3,5] , [3,6,5]]])
print(arr3d) 
print(arr3d.ndim) 

[[[1 2 3]
  [1 4 5]]

 [[1 3 5]
  [3 6 5]]]
3


crateing 10 or n dimension of array using ndmin = 10 , ndmin=dimension of array 


In [14]:
arrN = np.array([1,3,4,5] , ndmin=10 ) 
print(arrN , arrN.ndim) 


[[[[[[[[[[1 3 4 5]]]]]]]]]] 10


In [20]:
arrZero = np.zeros(4) 
arr2dZerro = np.zeros((2,3))  
print( arrZero , "\n ", arr2dZerro ) 


[0. 0. 0. 0.] 
  [[0. 0. 0.]
 [0. 0. 0.]]


***ones*** 


In [22]:
arr_one = np.ones((2,4) )
print(arrone) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#empty array 
arEm = np.empty(4 )
print(arEm) 


[0. 0. 0. 0.]


***Range***

In [103]:
ar_rn  = np.arange(4) 
array = np.arange(start=0, stop=10, step=1)

print(ar_rn) 
print(array) 

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


digonal 


In [28]:
ar_dia = np.eye(3,4) 
print(ar_dia) 
ar1 = np.eye(3) 
print(ar1) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


linspace(starting , ending , step )  with gap 


In [31]:
ar_lin = np.linspace(0 , 20 , 5 ) 
print(ar_lin) 


[ 0.  5. 10. 15. 20.]


## Random

##RAND()  : it only give  matrix of postive  random number 

In [34]:
randomArray = np.random.rand(4) 
print(randomArray) 
random2dArray = np.random.rand(2,5) 
print(random2dArray) 


[0.90609698 0.90918822 0.74044657 0.25518762]
[[0.78095759 0.7842857  0.01206668 0.70627457 0.30088625]
 [0.96522353 0.0995389  0.63205548 0.66621366 0.60338002]]


**randn()** it give matrix of negative and postive number 

In [37]:
print( np.random.randn(2,3) )

[[-0.26265809  0.46116835  1.09524007]
 [-1.11701331 -0.96765592 -0.23439531]]


## ranf()
it give matrix of number betweeb 0 to 1  and 1 is not  included  TAKES ONLY ONE ARGOUMENT 

In [5]:
print( np.random.ranf(2) )

[0.99863115 0.0433925 ]


## random.randint( start  , stop , totalNumbers  ) 
it genratete   number between two intigers 



In [44]:
print(np.random.randint(2,8) )
print(np.random.randint(2,9,5))

5
[2 6 5 8 3]


### Data types 

bool_

Boolean

int_

Default integer type (int64 or int32)

intc

Identical to the integer in C (int32 or int64)

intp

Integer value used for indexing

int8

8-bit integer value (-128 to 127)

int16

16-bit integer value (-32768 to 32767)

int32

32-bit integer value (-2147483648 to 2147483647)

int64

64-bit integer value (-9223372036854775808 to 9223372036854775807)

uint8

Unsigned 8-bit integer value (0 to 255)

uint16

Unsigned 16-bit integer value (0 to 65535)

uint32

Unsigned 32-bit integer value (0 to 4294967295)

uint64

Unsigned 64-bit integer value (0 to 18446744073709551615)

float_

Float values

float16

Half precision float values

float32

Single-precision float values

float64

Double-precision float values

complex_

Complex values

complex64

Represent two 32-bit float complex values (real and imaginary)

complex128

Represent two 64-bit float complex values (real and imaginary)

### U1 : string
### U11 : string and numbers 


In [45]:
var = np.array([1,3,4,5]) 
print('data type :' , var.dtype) 

data type : int64


* convert to another data type  

In [53]:
var2 = np.array([1,3,4,5] , dtype = np.uint64) 

print('data type: '  , var2.dtype) 
var3= np.array([1,3,4,5] , dtype = 'f') 
var4 = np.float32(var2 ) 


#astype function 
new_2 = var3.astype(float) 
print("astype " , new_2.dtype) 




data type:  uint64
astype  float64


## Arithmatic oppration in numpyt 

In [55]:
 var = np.array([1,3,5]) 
 add = var  + 2 
print(add ) 

[3 5 7]


In [56]:
var2 = np.array([2,4,5]) 
multi = var* var2 
print(multi) 

[ 2 12 25]


np.add(a,b ) 
np.subtract(a,b) 
mp.mod( a,b ) , for modulus 
np.power( a, b  ) a^b  a to the  power b 
np.reciprocal(a)  1/a 


**min( np.array())** : gives minimun number in the array

**max()** : givs maximum number in the arry

***argmax()*** gives postion or index of maximum number  of array 

**argmin()** gives postion or index of minimum number of array 

axis = 0  col -
col = 1 row |


In [63]:
arr2D_1= np.array([ [ 1 ,2 ,3 ] ,[1,2,3] ])
print( "postion of minimum ",np.argmin(arr2D_1 , axis=1))
print(" retuns row valu of maximum ",np.max(arr2D_1 , axis=1))

postion of minimum  [0 0]
valu of maximum  [3 3]


***np.sqrt()*** square root 

***np.sign()*** 

***np.cos()*** 



### cumsum() 
: np.cumsum([1 ,2, 3 ] ) = [ 1 , 1+2 , 1+2+3 ] 

## Shaping and reshaping in numpy 
### shape()

In [74]:
arr_3d_1 = np.array([1,3,4,2] , ndmin=3 ) 
arr_3d_2 = np.array([[1,3,4],[1,3,4],[1,3,4]] ) 

print(np.shape(arr_3d_1) ,'\n',np.shape(arr_3d_2)) 

(1, 1, 4) 
 (3, 3)


### reshape( no_of_rows , no_of_col ) 


In [105]:
print( arr_3d_1.reshape(2,2) ) 
print(arr_3d_1.reshape(4,1))


[[1 3]
 [4 2]]
[[1]
 [3]
 [4]
 [2]]


In [80]:
#3d reshapeing 
arr_3d_3= np.array([1,3,4,2,3,6, 4,9,6,3,6,7] ) 
#np.reshape(on_of_arry in  outer most dimension  , no  of array/row in 2d ,  no of col  ) 

oneD_3d = arr_3d_3.reshape( 2 , 3 , 2 )

print(  oneD_3d) 

# 3d to 1d 

oneD = oneD_3d.reshape(-1) 
print(oneD) 



[[[1 3]
  [4 2]
  [3 6]]

 [[4 9]
  [6 3]
  [6 7]]]
[1 3 4 2 3 6 4 9 6 3 6 7]


## Brodcasting in numpy 

if we try to perform arithmatic opraiton in uncompatible array then it will give ***brodcast Error*** 

example : if [ 1, 2, 3 ] + [1 ,3, 5,6]  we can not add this because the no of col are  more 

to perform the oprtionj ***the number of  colmun and Rows  should be same or one***

In [88]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Define a 5x3 matrix
B = np.array([[7, 8, 9],
              [10, 11, 12],
              [13, 14, 15],
              [16, 17, 18],
              [19, 20, 21]])
#add = A+B 
#print(add ) 
#getting 12
print(B[1,2])

C = np.array([[             [1, 2],
                             3, 4],
                             [5, 6],
                             [7, 8]],
                           
                            [[9, 10],
                             [11, 12],
                             [13, 14],
                             [15, 16]],
                           
                            [[17, 18],
                             [19, 20],
                             [21, 22],
                             [23, 24]]])

#getting 3 form 3d array  
print(C[0 ,1,0])

12
3


## slicing 
### arr[ start position : stop position -1: step ] 

In [92]:
arr_2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16] ) 
#                0 1 2 3 4 5 6 7 8 9
print(arr_2[2 : 8 :2 ] )
print("index 2 to end " ,  arr_2[2 :] ) 
print( " till index  5 "  , arr_2[ :6] ) 

[3 5 7]
index 2 to end  [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 till index  5  [1 2 3 4 5 6]


In [102]:
#sclicing in 2d array 

# getting 11 and 12 you can not  get data from another  row 
print( B[1,1:])

[11 12]


## itration 

In [109]:
for row in B  : 
    print(item ) 
    for col_item in row: 
        print(col_item)

[7 8 9]
7
8
9
[7 8 9]
10
11
12
[7 8 9]
13
14
15
[7 8 9]
16
17
18
[7 8 9]
19
20
21


### np.nditer(array)

In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Using np.nditer with different parameters


#whatch sperate this 
# Example 1: Basic iteration
print("Example 1: Basic Iteration")
for element in np.nditer(arr):
    print(element, end=' ')
print("\n")

# Example 2: Iteration with read-write access
print("Example 2: Iteration with Read-Write Access")
for element in np.nditer(arr, op_flags=['readwrite']):
    element[...] = element * 2
print("Modified Array:")
print(arr, "\n")

# Example 3: Iteration in reverse order
print("Example 3: Iteration in Reverse Order")
for element in np.nditer(arr, order='F'):
    print(element, end=' ')
print("\n")

# Example 4: Iteration with specific data type
print("Example 4: Iteration with Specific Data Type")
for element in np.nditer(arr, flags=['buffered'], op_dtypes=['int16']  , casting='same_kind') :
    print(element, end=' ')
print("\n")

# Example 5: Iteration with a different external loop
#print("Example 5: Iteration with a Different External Loop")
#arr_1d = np.arange(6)
#for element in np.nditer(arr, flags=['external_loop'], op_flags=['readonly'], external_loop=arr_1d):
#    print(element, end=' ')
#print("\n")

Example 1: Basic Iteration
1 2 3 4 5 6 

Example 2: Iteration with Read-Write Access
Modified Array:
[[ 2  4  6]
 [ 8 10 12]] 

Example 3: Iteration in Reverse Order
2 8 4 10 6 12 

Example 4: Iteration with Specific Data Type
2 4 6 8 10 12 



n the context of np.nditer in NumPy, the flags parameter allows you to specify additional behaviors during the iteration process. It's a way to customize how the iteration should occur. Let's break down the common flags and their meanings:

'c_index':

Meaning: It specifies that the iteration should follow C-order (row-major order).
In Simple Words: When iterating over a multi-dimensional array, it will go through the elements row by row.
'f_index':

Meaning: It specifies that the iteration should follow Fortran-order (column-major order).
In Simple Words: When iterating over a multi-dimensional array, it will go through the elements column by column.
'multi_index':

Meaning: It enables the use of a multi-index, meaning you get a tuple of indices for each element during iteration.
In Simple Words: Along with the value of the array element, you also get the indices (row, column, etc.) of that element.
'external_loop':

Meaning: It treats the input arrays as one-dimensional arrays with the last dimension varying the fastest.
In Simple Words: It flattens all dimensions except the last one, making the iteration appear as if it's over a 1D array.
'reduce_ok':

Meaning: It allows the iterator to be used in a reduction operation.
In Simple Words: It indicates that the iterator can be used in a reduction operation, such as computing the sum or product of the array elements.



### ndenumerate(array )  
gives the  index with datat 

In [117]:
#appling in 2d array data , postion , 2  ( 0 , 0 ) 

for index , data in  np.ndenumerate(arr) : 
    print (data , index ) 

2 (0, 0)
4 (0, 1)
6 (0, 2)
8 (1, 0)
10 (1, 1)
12 (1, 2)


### COPY VS VIEW 

***array.copy()*** 

create a new copy  and store the copied data  in new location , the data will not change even if orignal data changed 

***array.view()*** 

it just reffer  to similiar location of the orignal data , so when we will change the data the value will also changed 

In [119]:
arr1 = np.array( [1,2,3,4]) 
copiedData = arr1.copy() 
arr1[2] = 40 
print(arr1) 
print(copiedData) 

[ 1  2 40  4]
[1 2 3 4]


In [120]:
arr2 = np.array( [1,2,3,4]) 
viewData = arr1.view() 
arr1[2] = 40 
print(arr1) 
print(viewData) 

[ 1  2 40  4]
[ 1  2 40  4]


In [12]:
for i in np.nditer(arr, order='F') :
 print(i) 

2
8
4
10
6
12


## join array 

### np.concatenate( (array1, arr2) , axis=1) 

In [16]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])

arr3 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr4 = np.concatenate((arr1,arr3) , axis=1)
print(arr4) 

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## np.stack((arr1 , arr2 ) , axis=0 ) 

### np.hstack((arr1 ,arr2))
 merging along the row 

### np.vstack((arr1, arr2)) 
merging along the colmum 

### np.dstack((arr1 ,arr2 )) 
mergin  along to hight
means it take 2  2D arrays and create a 3D array 


In [19]:
print(  np.dstack((arr1 ,arr3 )) )

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


## Split 

### np.array_split(arry , no_of_splits , axis= 0  ) 
 axis is optional 
 it  splits a array and create a array of the dimension of parents array 
 

In [29]:
arr5= np.arange( start = 0 , stop= 10 ) 
print (arr5 ) 
splitedArry = np.array_split(arr5 ,2  ) 
print(splitedArry ) 

## to get one array for splited array , it return a  list of splited array 
splitedArry[1] 

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


array([5, 6, 7, 8, 9])

## Search array 

### np.where((arry) == 2 ) 
it return the postion of 2 in the array 

In [32]:
arr6 = np.array( [ 1,35,6,8,9 ,10,14]) 

#it return the postion of element where the remender is  0 
pos = np.where( ( arr6%2) == 0 ) 
print(pos) 

(array([2, 3, 5, 6]),)


## np.searchsorted( array ,  element , side="right" )  
serachsorted array tell the postion of element   ,  where that elment can be fit in a sorted  form both   side 
lef of  right , 

expample here  we want to chekk   where 5 is fit in the array of  1 to  8 

In [35]:
sorted_arr = np.array( [1,2,3,4,6,8]) 
# searching form left , and  left is defualt side 
pos = np.searchsorted( sorted_arr , 5 , side="left" ) 
print(pos)
#you can also pass the  list  , now it will tell where 5 , 6 ,7 will placed 
pos2 = np.searchsorted( sorted_arr ,[ 5 , 6,7], side="left" ) 
print(pos2 ) 

4
[4 4 5]


## sort array 

it sort the array    , numerical and alphabe 

In [40]:
arr = np.array([ "B" ,"a"  ,"c", "A" ,"b" , "C",] ) 
sortedArr = np.sort( arr) 
print(sortedArr) 

['A' 'B' 'C' 'a' 'b' 'c']


### filter Array 

In [42]:
filter = [ True ,False , True, False ,False,False  ] 
arr[filter] 

array(['B', 'c'], dtype='<U1')

### np.random.shuffle(array )
randomly shuffels  the array 

In [47]:
np.random.shuffle(sorted_arr) 
print(sorted_arr ) 

[4 6 2 8 1 3]


## np.unique(arr1 ) 
it retrun   all the data  in arry that are uniqe in the arry , remove duplicate 

data with index no 
np.unique( arr1 , return_index= True , return_counts = True ) 


In [50]:
arr = np.array([1,2,3,3,2,5,6,7,8,7]) 
print( np.unique(arr) ) 
print( np.unique( arr, return_index=True , return_counts=True ) )

[1 2 3 5 6 7 8]
(array([1, 2, 3, 5, 6, 7, 8]), array([0, 1, 2, 5, 6, 7, 8]), array([1, 2, 2, 1, 1, 2, 1]))


### np.resize( arry , ( row,col) ) 
it also resize the arry in 2d or 3d 


In [53]:
arry2d =np.resize( arr , ( 5 ,2 ) ) 
print(arry2d) 

[[1 2]
 [3 3]
 [2 5]
 [6 7]
 [8 7]]


## arry.flatten( order='f') 
## np.ravel( arr , order='c') 
it convert the arry into 1d arry 

'C' order (C-style, row-major order): Flattens the array in row-major order, meaning it iterates over the rows first, then the columns.
'F' order (Fortran-style, column-major order): Flattens the array in column-major order, meaning it iterates over the columns first, then the rows.
[[1, 2, 3],
 [4, 5, 6]]
'C' order flattening: 1, 2, 3, 4, 5, 6
'F' order flattening: 1, 4, 2, 5, 3, 6

'A' order ('K' order): This stands for "Any" order. It means that NumPy will choose the most appropriate order based on the memory layout of the array. If the array is in C-contiguous order, it will behave as if 'C' order is specified. If it's in Fortran-contiguous order, it will behave as if 'F' order is specified.



In [57]:
print( arry2d.flatten( order='c') )

[1 2 3 3 2 5 6 7 8 7]


In [58]:
print( np.ravel(arry2d , order='f') )

[1 3 2 6 8 2 3 5 7 7]


###  np.insert( arry , position , value , axis = 0 ) 
postion  is index no , valuse can ve ins list [ 2, 4,5]   if you want  to inserti in 2d arry you can use axis 

In [59]:
print ( np.insert( arr , 2 , 40 ) ) 

[ 1  2 40  3  3  2  5  6  7  8  7]


### np.append( arry ,  vlaues , axis= 0 ) 
add data in last of array 


 ## np.delete( arry , indexNO of targeted val ) 
 

In [61]:
print( np.delete( arr , 3 ) ) 

[1 2 3 2 5 6 7 8 7]


## np.matrix( [ [1,3,4] , [ 1,3,4]]) 
to create the matrix in  numpy 

np.array( list ) mulitpy lin [ 1 ,2 ] * [1,3] = 1 ,6 
but np.matrix perform dot multiplication 



In [69]:
arr1 = np.matrix([ [1,2 ] ,[1,3] ] ) 
arr2 = np.matrix([ [1,2 ] ,[1,3] ] ) 
print( arr1 * arr2 ) 
print( arr1.dot(arr2) ) 

## multiplication with array 
print()
arr3= np.array([[1, 2],
                [4, 5]])
print( arr3 * arr3 ) 

# to perform dot matrix not of rows must be uequal to no of  cos or vise versa 
print( arr3.dot(arr3) ) 

[[ 3  8]
 [ 4 11]]
[[ 3  8]
 [ 4 11]]

[[ 1  4]
 [16 25]]
[[ 9 12]
 [24 33]]


### transpose np.transpose( matrix )  / matrix.T

In [70]:
print( arr2.T) 

[[1 1]
 [2 3]]


##  np.swapaxes( matrix , 0 , 1) 
change the axis 
this is the exmape where we want to change  0 axix to 1 row to col 


In [72]:
print( np.swapaxes( arr2 , 0 , 1 ))  

[[1 1]
 [2 3]]


The inverse of a matrix A is denoted as A⁻¹ and is given by:

$$A^{-1} = \frac{1}{{\text{det}(A)}} \cdot \text{adj}(A) $$

where det(A) represents the determinant of matrix A, and adj(A) represents the adjugate (or adjoint) of matrix A.
### Determinant (det) of a matrix:

The determinant of a 2x2 matrix A is given by:

$$ \text{det}(A) = (a \cdot d) - (b \cdot c) $$

For a general 3x3 matrix A:

$$ \text{det}(A) = a(ei - fh) - b(di - fg) + c(dh - eg) $$

### Adjugate (adj) of a matrix:

The adjugate (or adjoint) matrix of A, denoted as adj(A), is obtained by taking the transpose of the cofactor matrix:

$$ \text{adj}(A) = \begin{bmatrix} C_{11} & C_{21} & \cdots & C_{n1} \\ C_{12} & C_{22} & \cdots & C_{n2} \\ \vdots & \vdots & \ddots & \vdots \\ C_{1n} & C_{2n} & \cdots & C_{nn} \end{bmatrix}^T $$

Where \( C_{ij} \) is the cofactor of the element at the ith row and jth column in matrix A.

### Example:

Consider the matrix A:

$$ A = \begin{bmatrix} 2 & 3 \\ 1 & 4 \end{bmatrix} $$

#### Determinant:

$$ \text{det}(A) = (2 \cdot 4) - (3 \cdot 1) = 8 - 3 = 5 $$

#### Adjugate:

Cofactor Matrix:

$$ \begin{bmatrix} 4 & -3 \\ -1 & 2 \end{bmatrix} $$

Adjugate Matrix:

$$ \text{adj}(A) = \begin{bmatrix} 4 & -1 \\ -3 & 2 \end{bmatrix} $$



### np.linalg.inv(matrix ) 
for inverse the matrix 


In [74]:
print( np.linalg.inv( arr2 ) ) 

[[ 3. -2.]
 [-1.  1.]]


## power of matrix , np.linalg.matrix_power( matrix , power )

np.linalg.matrix_power( m , n ) 

if n  = 0   return   inverse of matrix 

[[1,0]
[0,1]] 

if n > 0 : m^n 

if n< 0 : 

inverse of m *  n 


## Determinant  of matrix  np.linalg.det( matrix ) 

In [75]:
print( np.linalg.det(arr2))

1.0
