In [2]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.3186, 0.5440, 0.8863],
        [0.8876, 0.8502, 0.4334],
        [0.5038, 0.9483, 0.2235],
        [0.8358, 0.1127, 0.0220],
        [0.6116, 0.2478, 0.2266]])


In [5]:
y = torch.randn( 2 ,4 ) 
zeros = torch.zeros(2,3) 
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
range = torch.arange(10) 
range 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
X=range.reshape( 2, 5 ) 
X
print(X) 
#-1 calculate automatic 
Y = range.reshape( 2,-1) 
print(Y)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


## view works same as reshape 
If you just want to reshape tensors, use torch.reshape. If you're also concerned about memory usage and want to ensure that the two tensors share the same data, use torch.view.



In [11]:
range.view(2,5 ) 

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**slicing** 

In [12]:
range[0:4] 

tensor([0, 1, 2, 3])